# name: Manual Deploy to Windows IIS

# on: 
#   workflow_dispatch: # This creates the manual button!

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#       - name: Run Deployment Script
#         run: C:\deploy.bat


name: Manual Deploy to Windows IIS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Switch to selected branch
        run: |
          cd C:\Apps\class_management_system_3
          git fetch origin
          git checkout ${{ github.event.inputs.branch }}
          git pull origin ${{ github.event.inputs.branch }}

      - name: Clear Laravel cache
        run: |
          cd C:\Apps\class_management_system_3
          php artisan view:clear
          php artisan cache:clear

      - name: Run Deployment Script
        run: C:\deploy.bat
