# name: Manual Deploy to Windows IIS

# on: 
#   workflow_dispatch: # This creates the manual button!

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#       - name: Run Deployment Script
#         run: C:\deploy.bat


name: Manual Deploy to Windows IIS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'cms-test'

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: 'C:/Apps/class_management_system_3'

    steps:
      - name: Switch to selected branch
        run: |
          git fetch origin
          git reset --hard
          git checkout ${{ github.event.inputs.branch }}
          git pull origin ${{ github.event.inputs.branch }}

      - name: Clear Laravel cache
        run: |
          php artisan view:clear
          php artisan cache:clear
          php artisan config:clear

      - name: Run Deployment Script
        run: C:\deploy.bat
        working-directory: 'C:\'